[package]
name = "send_message"
version = "1.0.0"
authors = []

[addresses]
MyModule = '0x0636299e7623948e5b3c16001af9aedc0d26048b0f6e9707b762dd04c29d0987'
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]